---
# Developed by SexyLush
# Tags configuration file

# Version, recommended to not change
# version: 1.6.9

# SexyTags-For-PMMP
# Tags cannot be changed from a config or .yml, yet...
# You have to open the Main.php and continue the pattern for each and every tag you make if you get any errors feel free to contact me via discord (SexyLush#6969), same goes for commisions.
# This plugin is originally from my MCPE server TreasureWarps, IP & Port are hub.twpe.tk 19132!
# Enjoy!

# commands:
#   tags:
#     description: Opens Tags Menu
    
# permissions:
#  tags.noob:
#    description: noob Tag
#    default: true
#  tags.alien:
#    description: alien Tag
#    default: op
#  tags.bombom:
#    description: bombom Tag
#    default: op
#  tags.hacker:
#    description: hacker Tag
#    default: op
#  tags.spicy:
#    description: Spicy Tag
#    default: op
#  tags.sexylush:
#    description: SexyLush Tag to honour the developer
#    default: op
#  tags.og:
#    description: OG Tag
#    default: op
#  tags.dragon:
#    description: dragon Tag
#    default: op
#  tags.twpe:
#    description: TreausureWarps Tag
#    default: op
#  tags.aussieping:
#    description: pro Tag
#    default: op
#  tags.ed:
#    description: ed Tag
#    default: op
...
